### ISSUE TITLE
旧Sqlite数据迁移到MySQL

### ISSUE THREAD

**Issue by akarinini** [A-SoulFan/asasfans-api#1]
从sqlite数据库取出bvid和tag，再用https://api.bilibili.com/x/web-interface/view?bvid= 获取新的视频数据，存入mysql数据库中。sqlite中tag字段有两种情况，一种是由[‘’]包裹起来的，一种没有。需要统一把[‘’]去掉，另外由[‘’]包裹起来的tag中第一个tag是视频标题，也需要去除，这里最好不要用英文逗号作分隔去除，标题中也可能有英文逗号。
或者根据bvid去用https://api.bilibili.com/x/web-interface/view?bvid= 获取视频信息，用https://api.bilibili.com/x/web-interface/view/detail/tag?bvid= 获取tag，不使用sqlite中的tag

**Comment by RunsTp** [comment]
已完成
