### ISSUE TITLE
缺少一个邮件验证码模板

### ISSUE THREAD

**Issue by RunsTp** [A-SoulFan/asasfans-api#6]
目前发送邮箱验证码缺少好看的模板。
目前有以下几个方案

- 找个网站的temple改改
- 来个手子写一个

考虑到邮件html协议，如果有前端想帮忙，可以直接留言，我会告诉你注意事项

**Comment by oldking139** [comment]
一个参考（来自于nodebb默认html邮件验证模板），可任意修改。
![image](https://user-images.githubusercontent.com/45203648/164245995-613aa9fb-ff5a-4723-8a66-c141dcf2642e.png)

- https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/register.tpl
- https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/registerComplete.tpl
- https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/reset.tpl
- https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/reset_code.tpl

**Comment by RunsTp** [comment]
> 一个参考（来自于nodebb默认html邮件验证模板），可任意修改。 ![image](https://user-images.githubusercontent.com/45203648/164245995-613aa9fb-ff5a-4723-8a66-c141dcf2642e.png)
> 
> * https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/register.tpl
> * https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/registerComplete.tpl
> * https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/reset.tpl
> * https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/reset_code.tpl

好，如果没有更好的 我就用这个了
